using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TT2Advisor.Common.Enums
{
    public enum ArtifactTypeEnum
    {
        [Display(Name = "Not Set")] NotSet,
        [Display(Name = "Book of Shadows")] BookofShadows,
        [Display(Name = "Charged Card")] ChargedCard,
        [Display(Name = "Stone of the Valrunes")] StoneoftheValrunes,
        [Display(Name = "Chest of Contentment")] ChestofContentment,
        [Display(Name = "Heroic Shield")] HeroicShield,
        [Display(Name = "Book of Prophecy")] BookofProphecy,
        [Display(Name = "Khrysos Bowl")] KhrysosBowl,
        [Display(Name = "Zakynthos Coin")] ZakynthosCoin,
        [Display(Name = "Great Fay Medallion")] GreatFayMedallion,
        [Display(Name = "Neko Sculpture")] NekoSculpture,
        [Display(Name = "Coins of Ebizu")] CoinsofEbizu,
        [Display(Name = "The Bronzed Compass")] TheBronzedCompass,
        [Display(Name = "Evergrowing Stack")] EvergrowingStack,
        [Display(Name = "Flute of the Soloist")] FluteoftheSoloist,
        [Display(Name = "Heavenly Sword")] HeavenlySword,
        [Display(Name = "Divine Retribution")] DivineRetribution,
        [Display(Name = "Drunken Hammer")] DrunkenHammer,
        [Display(Name = "Samosek Sword")] SamosekSword,
        [Display(Name = "The Retaliator")] TheRetaliator,
        [Display(Name = "Stryfe's Peace")] StryfesPeace,
        [Display(Name = "Hero's Blade")] HerosBlade,
        [Display(Name = "The Sword of Storms")] TheSwordofStorms,
        [Display(Name = "Furies Bow")] FuriesBow,
        [Display(Name = "Charm of the Ancient")] CharmoftheAncient,
        [Display(Name = "Tiny Titan Tree")] TinyTitanTree,
        [Display(Name = "Helm of Hermes")] HelmofHermes,
        [Display(Name = "Fruit of Eden")] FruitofEden,
        [Display(Name = "Influential Elixir")] InfluentialElixir,
        [Display(Name = "Shimmering Oil")] ShimmeringOil,
        [Display(Name = "O'Ryan's Charm")] ORyansCharm,
        [Display(Name = "Heart of Storms")] HeartofStorms,
        [Display(Name = "Apollo Orb")] ApolloOrb,
        [Display(Name = "Sticky Fruit")] StickyFruit,
        [Display(Name = "Hades Orb")] HadesOrb,
        [Display(Name = "Earrings of Portara")] EarringsofPortara,
        [Display(Name = "Avian Feather")] AvianFeather,
        [Display(Name = "Corrupted Rune Heart")] CorruptedRuneHeart,
        [Display(Name = "Durendal Sword")] DurendalSword,
        [Display(Name = "Helheim Skull")] HelheimSkull,
        [Display(Name = "Oath's Burden")] OathsBurden,
        [Display(Name = "Crown of the Constellation")] CrownoftheConstellation,
        [Display(Name = "Titania's Sceptre")] TitaniasSceptre,
        [Display(Name = "Fagin's Grip")] FaginsGrip,
        [Display(Name = "Ring of Calisto")] RingofCalisto,
        [Display(Name = "Blade of Damocles")] BladeofDamocles,
        [Display(Name = "Helmet of Madness")] HelmetofMadness,
        [Display(Name = "Titanium Plating")] TitaniumPlating,
        [Display(Name = "Moonlight Bracelet")] MoonlightBracelet,
        [Display(Name = "Amethyst Staff")] AmethystStaff,
        [Display(Name = "Sword of the Royals")] SwordoftheRoyals,
        [Display(Name = "Spearit's Vigil")] SpearitsVigil,
        [Display(Name = "The Cobalt Plate")] TheCobaltPlate,
        [Display(Name = "Sigils of Judgement")] SigilsofJudgement,
        [Display(Name = "Foliage of the Keeper")] FoliageoftheKeeper,
        [Display(Name = "Invader's Gjalarhorn")] InvadersGjallarhorn,
        [Display(Name = "Titan's Mask")] TitansMask,
        [Display(Name = "Royal Toxin")] RoyalToxin,
        [Display(Name = "Laborer's Pendant")] LaborersPendant,
        [Display(Name = "Bringer of Ragnarok")] BringerofRagnarok,
        [Display(Name = "Parchment of Foresight")] ParchmentofForesight,
        [Display(Name = "Elixir of Eden")] ElixirofEden,
        [Display(Name = "Hourglass of the Impatient")] HourglassoftheImpatient,
        [Display(Name = "Phantom Timepiece")] PhantomTimepiece,
        [Display(Name = "Forbidden Scroll")] ForbiddenScroll,
        [Display(Name = "Ring of Fealty")] RingofFealty,
        [Display(Name = "Glacial Axe")] GlacialAxe,
        [Display(Name = "Aegis")] Aegis,
        [Display(Name = "Swamp Gauntlet")] SwampGauntlet,
        [Display(Name = "Infinity Pendulum")] InfinityPendulum,
        [Display(Name = "Glove of Kuma")] GloveofKuma,
        [Display(Name = "Titan Spear")] TitanSpear,
        [Display(Name = "Oak Staff")] OakStaff,
        [Display(Name = "The Arcana Cloak")] TheArcanaCloak,
        [Display(Name = "Hunter's Ointment")] HuntersOintment,
        [Display(Name = "Ambrosia Elixir")] AmbrosiaElixir,
        [Display(Name = "Mystic Staff")] MysticStaff,
        [Display(Name = "Mystical Beans of Senzu")] MysticalBeansofSenzu,
        [Display(Name = "Egg of Fortune")] EggofFortune,
        [Display(Name = "Divine Chalice")] DivineChalice,
        [Display(Name = "Invader's Shield")] InvadersShield,
        [Display(Name = "Axe of Muerte")] AxeofMuerte,
        [Display(Name = "Essence of the Kitsune")] EssenceoftheKitsune,
        [Display(Name = "Boots of Hermes")] BootsofHermes,
        [Display(Name = "Unbound Gauntlet")] UnboundGauntlet,
        [Display(Name = "Oberon Pendant")] OberonPendant,
        [Display(Name = "Lucky Foot of Al-mi'raj")] LuckyFootofAlmiraj,
        [Display(Name = "Lost King's Mask")] LostKingsMask,
        [Display(Name = "Staff of Radiance")] StaffofRadiance,
        [Display(Name = "Morgelai Sword")] MorgelaiSword,
        [Display(Name = "Ringing Stone")] RingingStone,
        [Display(Name = "Quill of Scrolls")] QuillofScrolls,
        [Display(Name = "Old King's Stamp")] OldKingsStamp,
        [Display(Name = "The Master's Sword")] TheMastersSword,
        [Display(Name = "The Magnifier")] TheMagnifier,
        [Display(Name = "The Treasure of Fergus")] TheTreasureofFergus,
        [Display(Name = "The White Dwarf")] TheWhiteDwarf,
        [Display(Name = "Aram Spear")] AramSpear,
        [Display(Name = "Ward of the Darkness")] WardoftheDarkness,
    }

}
